import type { Metadata } from "next";

import "./globals.css";
import {
  Sidebar
} from "@/components/elements"
import Provider from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`antialiased`}
          >
          <Provider>
            <div className="flex flex-col md:flex-row md:justify-between md:space-x-[15rem]">
              <Sidebar />
              {children}
            </div>
        </Provider>
        </body>
    </html>
  );
}
